In [ ]:
import pickle
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('loan_detection.csv')
df

,age,campaign,pdays,previous,no_previous_contact,not_working,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,...,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success,Loan_Status_label
0,56,1,999,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
1,57,1,999,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
2,37,1,999,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
3,40,1,999,0,1,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
4,56,1,999,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,1,999,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,1
41184,46,1,999,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0
41185,56,2,999,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
41186,44,1,999,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,1
41187,74,3,999,1,1,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0

In [ ]:
df.columns

Index(['age', 'campaign', 'pdays', 'previous', 'no_previous_contact',
       'not_working', 'job_admin.', 'job_blue-collar', 'job_entrepreneur',
       'job_housemaid', 'job_management', 'job_retired', 'job_self-employed',
       'job_services', 'job_student', 'job_technician', 'job_unemployed',
       'job_unknown', 'marital_divorced', 'marital_married', 'marital_single',
       'marital_unknown', 'education_basic.4y', 'education_basic.6y',
       'education_basic.9y', 'education_high.school', 'education_illiterate',
       'education_professional.course', 'education_university.degree',
       'education_unknown', 'default_no', 'default_unknown', 'default_yes',
       'housing_no', 'housing_unknown', 'housing_yes', 'loan_no',
       'loan_unknown', 'loan_yes', 'contact_cellular', 'contact_telephone',
       'month_apr', 'month_aug', 'month_dec', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'day_of_week_fri', 'day_of_week_mon', 'day_of_week_thu',
       'day_of_week_tue', 'day_of_week_wed', 'poutcome_failure',
       'poutcome_nonexistent', 'poutcome_success', 'Loan_Status_label'],
      dtype='object')

In [ ]:
df.isnull().sum()

age                              0
campaign                         0
pdays                            0
previous                         0
no_previous_contact              0
not_working                      0
job_admin.                       0
job_blue-collar                  0
job_entrepreneur                 0
job_housemaid                    0
job_management                   0
job_retired                      0
job_self-employed                0
job_services                     0
job_student                      0
job_technician                   0
job_unemployed                   0
job_unknown                      0
marital_divorced                 0
marital_married                  0
marital_single                   0
marital_unknown                  0
education_basic.4y               0
education_basic.6y               0
education_basic.9y               0
education_high.school            0
education_illiterate             0
education_professional.course    0
education_university.degree      0
education_unknown                0
default_no                       0
default_unknown                  0
default_yes                      0
housing_no                       0
housing_unknown                  0
housing_yes                      0
loan_no                          0
loan_unknown                     0
loan_yes                         0
contact_cellular                 0
contact_telephone                0
month_apr                        0
month_aug                        0
month_dec                        0
month_jul                        0
month_jun                        0
month_mar                        0
month_may                        0
month_nov                        0
month_oct                        0
month_sep                        0
day_of_week_fri                  0
day_of_week_mon                  0
day_of_week_thu                  0
day_of_week_tue                  0
day_of_week_wed                  0
poutcome_failure                 0
poutcome_nonexistent             0
poutcome_success                 0
Loan_Status_label                0
dtype: int64

In [ ]:
df.drop_duplicates(keep='first',inplace=True)

In [ ]:
df

,age,campaign,pdays,previous,no_previous_contact,not_working,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,...,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success,Loan_Status_label
0,56,1,999,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
1,57,1,999,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
2,37,1,999,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
3,40,1,999,0,1,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
4,56,1,999,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,1,999,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,1
41184,46,1,999,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0
41185,56,2,999,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
41186,44,1,999,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,1
41187,74,3,999,1,1,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0

In [ ]:
df['Loan_Status_label'].value_counts()

Loan_Status_label
0    34179
1     4592
Name: count, dtype: int64

In [ ]:
from sklearn.utils import resample
rejected = df[df['Loan_Status_label']==0]
approved = df[df['Loan_Status_label']==1]
rejected_down = resample(rejected,n_samples=len(approved),random_state=42,replace=False)
df = pd.concat([rejected_down,approved])
df

,age,campaign,pdays,previous,no_previous_contact,not_working,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,...,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success,Loan_Status_label
7778,29,3,999,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
21384,31,4,999,0,1,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
29028,35,1,999,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
12037,42,5,999,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0
34084,39,3,999,1,1,0,0,1,0,0,...,0,0,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41173,62,1,999,2,1,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
41174,62,1,1,6,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,1,1
41178,62,2,6,3,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,1,1
41183,73,1,999,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,1
41186,44,1,999,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,1

In [ ]:
df['Loan_Status_label'].value_counts()

Loan_Status_label
0    4592
1    4592
Name: count, dtype: int64

In [ ]:
corr_target = df.corr()["Loan_Status_label"].sort_values(ascending=False)
print(corr_target)

Loan_Status_label                1.000000
poutcome_success                 0.291255
previous                         0.250668
contact_cellular                 0.249043
default_no                       0.171870
not_working                      0.156367
month_oct                        0.154688
month_mar                        0.138718
month_sep                        0.131937
job_retired                      0.120255
job_student                      0.105204
month_apr                        0.102826
marital_single                   0.093474
month_dec                        0.074092
education_university.degree      0.073971
job_admin.                       0.051674
age                              0.047294
poutcome_failure                 0.040465
day_of_week_thu                  0.028420
education_unknown                0.027412
housing_yes                      0.023119
loan_no                          0.022369
job_unemployed                   0.017893
education_illiterate             0.014004
day_of_week_tue                  0.009496
marital_unknown                  0.006839
day_of_week_wed                  0.004616
education_professional.course    0.001302
job_self-employed               -0.000614
job_unknown                     -0.001226
month_aug                       -0.003114
job_technician                  -0.007410
education_basic.4y              -0.008905
loan_unknown                    -0.009117
housing_unknown                 -0.009117
job_management                  -0.010417
default_yes                     -0.010435
job_housemaid                   -0.011197
day_of_week_fri                 -0.015862
education_high.school           -0.016833
month_jun                       -0.019609
loan_yes                        -0.019820
housing_no                      -0.020365
job_entrepreneur                -0.022282
month_nov                       -0.023294
day_of_week_mon                 -0.028061
marital_divorced                -0.032986
education_basic.6y              -0.040101
month_jul                       -0.048118
job_services                    -0.063041
marital_married                 -0.066628
education_basic.9y              -0.069348
job_blue-collar                 -0.119958
campaign                        -0.131103
default_unknown                 -0.171619
month_may                       -0.185146
poutcome_nonexistent            -0.245935
contact_telephone               -0.249043
no_previous_contact             -0.300619
pdays                           -0.300654
Name: Loan_Status_label, dtype: float64

In [ ]:
important_features = corr_target[abs(corr_target)>0.05]
important_features.drop('Loan_Status_label',inplace=True)
important_features.index

Index(['poutcome_success', 'previous', 'contact_cellular', 'default_no',
       'not_working', 'month_oct', 'month_mar', 'month_sep', 'job_retired',
       'job_student', 'month_apr', 'marital_single', 'month_dec',
       'education_university.degree', 'job_admin.', 'job_services',
       'marital_married', 'education_basic.9y', 'job_blue-collar', 'campaign',
       'default_unknown', 'month_may', 'poutcome_nonexistent',
       'contact_telephone', 'no_previous_contact', 'pdays'],
      dtype='object')

In [ ]:
X = df[important_features.index]
y = df['Loan_Status_label']

In [ ]:
X

,poutcome_success,previous,contact_cellular,default_no,not_working,month_oct,month_mar,month_sep,job_retired,job_student,...,marital_married,education_basic.9y,job_blue-collar,campaign,default_unknown,month_may,poutcome_nonexistent,contact_telephone,no_previous_contact,pdays
7778,0,0,0,1,0,0,0,0,0,0,...,0,0,0,3,0,0,1,1,1,999
21384,0,0,1,1,0,0,0,0,0,0,...,0,0,0,4,0,0,1,0,1,999
29028,0,0,1,1,0,0,0,0,0,0,...,1,0,0,1,0,0,1,0,1,999
12037,0,0,0,0,0,0,0,0,0,0,...,1,1,1,5,1,0,1,1,1,999
34084,0,1,1,1,0,0,0,0,0,0,...,0,0,1,3,0,1,0,0,1,999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41173,0,2,1,1,1,0,0,0,1,0,...,1,0,0,1,0,0,0,0,1,999
41174,1,6,1,1,1,0,0,0,1,0,...,1,0,0,1,0,0,0,0,0,1
41178,1,3,1,1,1,0,0,0,1,0,...,1,0,0,2,0,0,0,0,0,6
41183,0,0,1,1,1,0,0,0,1,0,...,1,0,0,1,0,0,1,0,1,999
41186,0,0,1,1,0,0,0,0,0,0,...,1,0,0,1,0,0,1,0,1,999

In [ ]:
y

7778     0
21384    0
29028    0
12037    0
34084    0
        ..
41173    1
41174    1
41178    1
41183    1
41186    1
Name: Loan_Status_label, Length: 9184, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
X_train

,poutcome_success,previous,contact_cellular,default_no,not_working,month_oct,month_mar,month_sep,job_retired,job_student,...,marital_married,education_basic.9y,job_blue-collar,campaign,default_unknown,month_may,poutcome_nonexistent,contact_telephone,no_previous_contact,pdays
39535,0,0,1,1,0,0,0,0,0,0,...,0,0,0,3,0,0,1,0,1,999
39219,0,0,1,1,0,0,1,0,0,0,...,0,0,1,1,0,0,1,0,1,999
35226,0,1,1,1,0,0,0,0,0,0,...,1,1,1,2,0,1,0,0,1,999
24118,0,0,1,1,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,1,999
5231,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,1,1,1,1,999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24062,0,0,0,1,0,1,0,0,0,0,...,1,0,0,1,0,0,1,1,1,999
14919,0,0,1,1,0,0,0,0,0,0,...,1,0,1,2,0,0,1,0,1,999
18114,0,0,1,1,0,0,0,0,0,0,...,1,0,0,1,0,0,1,0,1,999
10745,0,0,0,1,0,0,0,0,0,0,...,0,0,0,2,0,0,1,1,1,999
36975,0,0,1,1,0,0,0,0,0,0,...,0,0,0,2,0,0,1,0,1,999

In [ ]:
X_test

,poutcome_success,previous,contact_cellular,default_no,not_working,month_oct,month_mar,month_sep,job_retired,job_student,...,marital_married,education_basic.9y,job_blue-collar,campaign,default_unknown,month_may,poutcome_nonexistent,contact_telephone,no_previous_contact,pdays
27802,0,0,1,1,1,0,1,0,1,0,...,0,0,0,2,0,0,1,0,1,999
29265,0,0,1,1,0,0,0,0,0,0,...,1,0,0,3,0,0,1,0,1,999
30752,0,0,1,1,0,0,0,0,0,0,...,0,1,1,2,0,1,1,0,1,999
10661,0,0,0,1,0,0,0,0,0,0,...,1,0,0,4,0,0,1,1,1,999
33956,0,1,1,1,0,0,0,0,0,0,...,0,0,1,1,0,1,0,0,1,999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22318,0,0,1,1,0,0,0,0,0,0,...,1,0,0,9,0,0,1,0,1,999
18103,0,0,1,1,1,0,0,0,0,0,...,0,0,0,2,0,0,1,0,1,999
27088,0,1,1,1,0,0,0,0,0,0,...,1,0,0,4,0,0,0,0,1,999
35956,0,0,1,1,0,0,0,0,0,0,...,0,0,0,4,0,1,1,0,1,999
1352,0,0,0,1,0,0,0,0,0,0,...,1,0,0,2,0,1,1,1,1,999

In [ ]:
y_train

39535    1
39219    1
35226    0
24118    1
5231     0
        ..
24062    1
14919    1
18114    1
10745    0
36975    1
Name: Loan_Status_label, Length: 6428, dtype: int64

In [ ]:
y_test

27802    1
29265    1
30752    0
10661    1
33956    0
        ..
22318    0
18103    1
27088    0
35956    1
1352     0
Name: Loan_Status_label, Length: 2756, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler

sr = StandardScaler()

In [ ]:
X_train = sr.fit_transform(X_train)
X_test = sr.transform(X_test)

In [ ]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [ ]:
print("Training Score: ",lr.score(X_train,y_train))
print("Testing Score",lr.score(X_test,y_test))

Training Score:  0.6873055382700685
Testing Score 0.6897677793904209

In [ ]:

dt = DecisionTreeClassifier(max_depth=9)
dt.fit(X_train,y_train)
print(i,"Training Score: ",dt.score(X_train,y_train))
print(i,"Testing Score",dt.score(X_test,y_test))

NameError: name 'i' is not defined

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=9)
rf.fit(X_train,y_train)

In [ ]:
print("Training Score: ",rf.score(X_train,y_train))
print("Testing Score",rf.score(X_test,y_test))

In [ ]:
y_pred_train = rf.predict(X_train)
y_pred_test = rf.predict(X_test)

In [ ]:
print(confusion_matrix(y_train, y_pred_train))

In [ ]:
print(classification_report(y_train,y_pred_train))

In [ ]:
print(confusion_matrix(y_test, y_pred_test))

In [ ]:
print(classification_report(y_test, y_pred_test))

In [ ]:
from sklearn.metrics import roc_auc_score

probs = rf.predict_proba(X_test)[:,1]
print("AUC:",roc_auc_score(y_test, probs))

In [ ]:
selected_features = list(X.columns)
print(selected_features)

In [ ]:
import pickle

pickle.dump(selected_features, open("features.pkl","wb"))
pickle.dump(rf, open("model.pkl","wb"))